name: soryn
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev
    steps:
      - name: Dependencies
        run: |
          apk add clang build-base automake autoconf zlib-dev python3 zip curl unzip sudo

      - name: cloning and building lastest pspsdk
        run: | 
          git clone https://github.com/pspdev/pspsdk

      - name: bootstrap sdk and build
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make
          make install

      - name: checkout
        uses: actions/checkout@v4 
        with:
          submodules: recursive

      - name: update psp-cfw-sdk
        run: curl -OJL "https://github.com/pspdev/psp-cfw-sdk/releases/download/latest/psp-cfw-sdk.zip"
      
      - name: extract psp-cfw-sdk
        run: sudo unzip -o psp-cfw-sdk.zip -d /

      - name: build
        run:  make clean && make 

      - name: compress
        run: |
          cd dist
          zip -r ../soryn.zip .
      
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: soryn-release
          path: soryn.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: soryn-release
          path: .
      - name:
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: soryn pre-release
          prerelease: true
          files: soryn.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    
